import json
from datetime import datetime, timezone
from pathlib import Path


def main():
    repo_root = Path(__file__).resolve().parent.parent
    data_dir = repo_root / "data"
    data_dir.mkdir(exist_ok=True)

    events_path = data_dir / "events.json"

    sample_events = [
        {
            "source": "OpenAI",
            "category": "core_tech",
            "title": "Sample signal placeholder",
            "url": "https://example.com",
            "published_at": datetime.now(timezone.utc).isoformat(),
            "summary": "This is a placeholder event generated by the automation pipeline.",
            "signal_type": "model_capability",
            "importance_score": 5,
            "theme_tags": ["automation", "placeholder"]
        }
    ]

    with open(events_path, "w", encoding="utf-8") as f:
        json.dump(sample_events, f, indent=2, ensure_ascii=False)

    print(f"Wrote {len(sample_events)} event(s) to {events_path}")


if __name__ == "__main__":
    main()
